version: "3.3"
services:
    backend:
        build: .
        container_name: node-backend
        ports:
            - 8000:8000
        restart: always
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        ports:
            - 3001:5432
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

